service: restaurant-service

provider:
  name: aws
  runtime: nodejs16.x
  timeout: 8
  versionFunctions: false
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  restaurants:
    handler: handler.restaurants
    events:
      - http:
          path: /restaurants
          method: ANY

  restaurant-food:
    handler: handler.restaurantFood
    events:
      - http:
          path: /restaurants/{restaurantId}/food
          method: ANY

  create-order:
    handler: handler.createOrder
    events:
      - http:
          path: /orders
          method: POST

  get-order:
    handler: handler.getOrder
    events:
      - http:
          path: /orders/{orderId}
          method: GET

  get-restaurant-orders:
    handler: handler.getRestaurantOrders
    events:
      - http:
          path: /restaurants/{restaurantId}/orders
          method: GET

  get-food-with-restaurants:
    handler: handler.getFoodWithRestaurants
    events:
      - http:
          path: /food-with-restaurants
          method: GET

resources:
  Resources:
    RestaurantsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Restaurants
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    FoodTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Food
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Orders
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

package:
  patterns:
    - "!node_modules/**"
